var defaultBrackets = {
    teams: [[{
        race: "",
        name: "Durkan"
    }, {
        race: "",
        name: "Flop"
    }], [{
        race: "",
        name: "motchi"
    }, {
        race: "",
        name: "Ulver"
    }], [{
        race: "P",
        name: "crow"
    }, {
        race: "P",
        name: "MrGreen"
    }], [{
        race: "",
        name: "Melkor"
    }, {
        race: "",
        name: "Ombre"
    }], [{
        race: "P",
        name: "KarlsBerg"
    }, {
        race: "Z",
        name: "ThgX"
    }], [{
        race: "",
        name: "Samii"
    }, {
        race: "",
        name: "Rultane"
    }], [{
        race: "P",
        name: "Evilz"
    }, {
        race: "T",
        name: "Air"
    }], [{
        race: "Z",
        name: "Neths"
    }, {
        race: "T",
        name: "skilo"
    }], [{
        race: "P",
        name: "fidzysss"
    }, {
        race: "Z",
        name: "Aldogan"
    }], [{
        race: "T",
        name: "Vrowgh"
    }, {
        race: "Z",
        name: "tahitiBob"
    }], [{
        race: "",
        name: "Mout"
    }, {
        race: "",
        name: "Limbshaft"
    }], [{
        race: "P",
        name: "Wayepi"
    }, {
        race: "T",
        name: "darkyokai"
    }], [{
        race: "",
        name: "CoolSpot"
    }, {
        race: "",
        name: "safir"
    }], [{
        race: "Z",
        name: "suistrop"
    }, {
        race: "",
        name: "Pulsions"
    }], [{
        race: "",
        name: "Sebi"
    }, {
        race: "",
        name: "Bobo"
    }], [{
        race: "P",
        name: "HellOne"
    }, {
        race: "P",
        name: "Zimbali"
    }]],
    results: [[[[0, 2], [2, 0], [2, 0], [2, 1], [2, 0], [2, 0], [2, 0], [2, 1], [2, 0], [2, 0], [0, null], [2, 0], [2, 1], [2, 0], [2, 0], [2, 0]], [[null, null], [null, null], [null, null], [2, 0], [2, 0], [null, null], [null, null], [null, null]], [[null, null], [null, null], [null, null], [null, null]], [[null, null], [null, null]], [[null, null], [null, null]]]]

}
